### ISSUE TITLE
Using the docker container with more advanced options

### ISSUE THREAD

**Issue by JarnoRFB** [vivekratnavel/omniboard#5]
Hey, looks like a cool project!

I tried to start it in a container, linking it to my existing mongo container for which SCRAM-SHA authentification is enabled like so

`docker run -it --rm -p 9000:9000 --name omniboard --network sacred_network vivekratnavel/omniboard "--mu mongodb://user:pwd@mongo:27017/?authMechanism=SCRAM-SHA-1 db"`

I used `--network` instead of `--link` as I could not link the container running not in the default network. 

However, after startup I get the following error

```
Database connection error:  { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/usr/omniboard/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at Pool.emit (events.js:182:13)
    at Connection.<anonymous> (/usr/omniboard/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:182:13)
    at Socket.<anonymous> (/usr/omniboard/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:189:49)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  name: 'MongoError',
  message:
   'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }
```

So I believe it should try to connect to  `mongo:27017` instead of  `127.0.0.1:27017`. Am I missing something or might this be a bug?

Thank you for your support!

**Comment by vivekratnavel** [comment]
Thanks for trying it out!
Can you try ```docker run -it --rm -p 9000:9000 --name omniboard --network sacred_network --link YOUR_MONGODB_CONTAINER:mongo vivekratnavel/omniboard "--mu mongodb://user:pwd@mongo:27017/?authMechanism=SCRAM-SHA-1 db" ``` ?

```YOUR_MONGODB_CONTAINER:mongo``` This reference is what we use in this connection string ```mongodb://user:pwd@mongo:27017```. So, without the link, it won't work.

**Comment by JarnoRFB** [comment]
Unfortunately, that produces exactly the same error. I also think that it should not make a difference as the mongo container, in the network should be named `mongo`. For comparison, I use the following `docker-compose` file to run the mongo container:

```
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pwd
    expose:
      - 27017
    networks:
      - sacred_network
```

**Comment by vivekratnavel** [comment]
In that case, did you try running omniboard with ```docker-compose``` as well? You can use ```command: --mu mongodb://user:pwd@mongo:27017/?authMechanism=SCRAM-SHA-1 db``` to pass arguments to omniboard

**Comment by JarnoRFB** [comment]
I tried 
```
  omniboard:
    image: vivekratnavel/omniboard
    command: ["--mu", "mongodb://user:pwd@mongo:27017/?authMechanism=SCRAM-SHA-1", "db"]
    networks:
      - sacred_network
    ports:
      - 9000:9000
```
this somehow produces 
```
name: 'MongoError',
omniboard_1      |   message:
omniboard_1      |    'only DEFAULT, GSSAPI, PLAIN, MONGODB-X509, SCRAM-SHA-1 or MONGODB-CR is supported by authMechanism',
omniboard_1      |   driver: true }
```

this seems really strange to me.
