### ISSUE TITLE
Using Kubernetes to run Omniboard latest image, previous issue raise

### ISSUE THREAD

**Issue by Chenguoqing2008** [vivekratnavel/omniboard#70]
I am using Kubernetes to run Omniboard latest image
```
containers:
        - name: omniboard
          image: vivekratnavel/omniboard:latest
          imagePullPolicy: Always
```

but i found that the previous version issues still exist. Such as it can't filter the experiment by "Running" status.

Can you double check it whether the image was build correctly? Thanks.
